name: Build WhatsApp

# Controls when the workflow will run
on:
  schedule: [{cron: "0 0 * * *"}]
  workflow_dispatch:
  push: {branches: ["main"]}

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Setup Node.js environment
        uses: actions/setup-node@v2.5.1
      
      # Runs a single command using the runners shell
      - name: Install nativefier and Git LFS
        run: |
          npm install -g nativefier && sudo apt install git-lfs

      - name: Build WhatsApp 
        run: bash ./build-whatsapp.sh
          
      #- name: Recreate repository
      #  run: gh repo delete --confirm && gh repo create --public whatsapp-for-linux --remote origin  -s .
      #  env:
      #    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name : Upload
        run : |
          rm -rf .git
          git init
          git lfs install
          git lfs track "*.deb"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config user.name "github-actions[bot]"
          git add .
          git commit -m "Update WhatsApp"
          git push --set-upstream origin master -f 
        
